#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDL-NAIF
version:      0.1
version_from: 
installdirs:  site
requires:
    PDL:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
